Moving to KTS
KotlinersKt/SingleFileScalableLasagnaApplication pull request #6
Opened 2020-09-09 08:06 UTC by sierisimo

- Moving settings and build at project level to kts
- Moving app build to kts

2020-09-17 09:47 UTC, gorrotowi requested changes
Creo el principal cambio que se debería de hacer es la versión de kotlin que se está usando

2020-09-17 09:47 UTC, gorrotowi commented on build.gradle.kts
> +        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72")
Por qué no usar 1.4.10 ?

2020-09-17 09:47 UTC, gorrotowi commented on app/build.gradle.kts
> +    id("kotlin-android-extensions")
Aquí también se podría usar kotlin("android.extensions")

2020-09-17 23:01 UTC, sierisimo commented on build.gradle.kts
> +        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72")
El PR es sobre movernos a KTS, una vez que estemos ahi podemos hacer un PR por separado para la migracion a 1.4

2020-09-17 23:01 UTC, sierisimo commented on app/build.gradle.kts
> +    id("kotlin-android-extensions")
Seguro? En mi experiencia luego tiene problemas ese plugin...

2020-09-22 06:09 UTC, gorrotowi approved these changes

2020-09-22 06:09 UTC, gorrotowi commented
LGTM 👍

2020-09-22 06:34 UTC, gorrotowi commented
@ChubyAvodroc lo puedes revisar o nomás decir "si va"? Sabemos que estás ocupado siendo guapito pero una ayuda diga estaría bien de vez en cuando

2020-09-22 06:42 UTC, ChubyAvodroc approved these changes
Si va, pero pues checar los comentarios

2020-09-22 06:42 UTC, ChubyAvodroc commented on app/build.gradle.kts
> +
Remove wild empty space

2020-09-22 06:42 UTC, ChubyAvodroc commented on app/build.gradle.kts
> +    kotlinOptions {
Add empty space

2020-09-22 06:42 UTC, ChubyAvodroc commented on build.gradle.kts
> +    dependencies {
Add empty space

2020-09-22 14:07 UTC, merged